### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'translate'

### ISSUE THREAD

**Issue by renzilin** [crohrandt/nanopore_simulation#6]
Dear author,

I met a problem about running simulatION. The error is shown below.

The python version I used is 3.5; the numpy version is 1.15.2.

The th01_0.fasta is a sequence whose length is around 170 bp.

Best,
Zilin

```
$SI/bin/simulatION simulate -r ../fasta/th01_editted/th01_0.fasta -m $SI/examples/DNA/template_median68pA.model -c $SI/examples/DNA/gDNAWA01.sic -n 5 -o th01
Loading config file
Loading reference genome. May take some time depending on genome size.
Loading model file
/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/simulatION-0.3-py3.5.egg/simulation/SimSignalGenerator.py:42: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  self.model_data = np.genfromtxt(model_file, delimiter="\t", dtype=None, comments='#', names=True)
/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/scipy/signal/signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
Traceback (most recent call last):
  File "/mnt/c/Users/ren-z/Documents/git_repos/Project_deepForensicSTR/tools/nanopore_simulation/bin/simulatION", line 36, in <module>
    args.func(parser, args)
  File "/mnt/c/Users/ren-z/Documents/git_repos/Project_deepForensicSTR/tools/nanopore_simulation/bin/simulatION", line 12, in run_subtool
    submodule.run(parser, args)
  File "/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/simulatION-0.3-py3.5.egg/simulation/simulate.py", line 45, in run
    reads = my_generator.generate(sub_number_reads,sampling_rate=my_generator.signal_config.sampling_rate,cut_off_freq=args.cut_off,bandwidth_freq=args.band)
  File "/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/simulatION-0.3-py3.5.egg/simulation/SimSignalGenerator.py", line 157, in generate
    new_record = list(Seq.reverse_complement(seq))
  File "/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/Bio/Seq.py", line 2736, in reverse_complement
    return complement(sequence)[::-1]
  File "/home/renz/miniconda3/envs/SimulatION/lib/python3.5/site-packages/Bio/Seq.py", line 2774, in complement
    return sequence.translate(ttable)
AttributeError: 'numpy.ndarray' object has no attribute 'translate'
```

**Comment by renzilin** [comment]
![image](https://user-images.githubusercontent.com/17135904/85904430-b70a2080-b7d6-11ea-9874-879312a17e9f.png)

`''.join(seq)` substitute the `seq` will work.
